[package]
name = "grimoire"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
rust-bert = "0.23.0"
rustc-hash = "2.1.1"
serde = { version = "1.0.219", features = ["derive"] }
tch = "0.17.0"
